language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs-v1"
 - "iojs-v2"

notifications:
  email:
    - dcoates@mozilla.com
    - achilton@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa"
    use_notice: false
    skip_join: false

before_install:
  - npm config set spin false

before_script:
  - npm i grunt-cli -g
  - npm run outdated

install:
  - npm install

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "iojs-v1"
    - node_js: "iojs-v2"
  fast_finish: true
